### ISSUE TITLE
Is the 6.0 NewArea not yet supported?

### ISSUE THREAD

**Issue by kkk30** [mushroom8009/AutheryteHelper#1]
you can only select the following three options...
Gridania
Limsa
Uldah
...

**Comment by mushroom8009** [comment]
I'm in the process of creating an explanation.
The teleport button is for when you want to do a world visit.
In the new version(0.9.5), the name has been changed, 
but if you put a checkmark at the top and go to the EW area's Aetheryte, you can select an instance with one button.

If you want a teleport button, I can make one. ....
Seems like a distraction to me.

Also, this is not fully automatic, but an aid.
You will need to do things like move around by yourself.


**I hurriedly created an explanation.
Please read the wiki.**
